baseURL = ""
languageCode = "en-us"
title = "Integreatly Website"
relativeURLs = true
disablePathToLower = true

[params]
    recent_posts_number = 10

[menu]

[[menu.main]]
  name = "Home"
  weight = 1
  identifier = "home"
  url = "/"

[[menu.main]]
  name = "Docs"
  weight = 2
  identifier = "docs"
  url = "/docs/getting-started.html"

[[menu.main]]
  name = "Getting started"
  weight = 1
  identifier = "getting_started"
  url = "/docs/getting-started.html"
  parent = "docs"

[[menu.main]]
  name = "Release Notes"
  weight = 2
  identifier = "release_notes"
  url = "/docs/release-notes.html"
  parent = "docs"

[[menu.main]]
  name = "Solution Patterns"
  weight = 3
  identifier = "walkthroughs"
  url = "/docs/walkthroughs.html"
  parent = "docs"

[[menu.main]]
  name = "Community"
  weight = 3
  identifier = "comm"
  url = "/i8y-community/"

[[menu.main]]
  name = "Contributing"
  weight = 1
  identifier = "contributing"
  url = "/i8y-community/contributing/"
  parent = "comm"

[[menu.main]]
  name = "Team"
  weight = 2
  identifier = "team"
  url = "/i8y-community/team/"
  parent = "comm"

[[menu.main]]
  name = "News"
  weight = 4
  identifier = "news"
  url = "/news/"
