site:
  title: Integreatly Docs
  start_page: docs::getting-started.adoc

content:
  sources:
    - url: https://github.com/milenazuccarelli/i8y.git
      branches: master

ui:
  bundle:
    url: ./i8y-ui-bundle/build/ui-bundle.zip

urls:
  redirect_facility: disabled

output:
  dir: ./static
